packages:
  - astro
  - express
  - frontend

# Settings <https://pnpm.io/settings>

## Dependency Resolution

minimumReleaseAgeExclude:
  - '@astrojs/markdown-satteri@0.3.1'
  - '@astrojs/node@11.0.0'
  - astro@7.0.0
  - js-yaml@5.1.0
  - node-html-parser@8.0.3
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3 # @astrojs/check@0.9.8 <https://github.com/withastro/astro/blob/main/packages/language-tools/astro-check/package.json>
  - semver@6.3.1 # eslint-plugin-import@2.32.0 <https://github.com/import-js/eslint-plugin-import/blob/main/package.json>
blockExoticSubdeps: true

## Dependency Hoisting Settings

publicHoistPattern:
  - 'eslint'
  - 'markuplint'
  - 'stylelint'

## Peer Dependency Settings

strictPeerDependencies: true

## CLI Settings

engineStrict: true

## Build Settings

strictDepBuilds: true
allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
