packages:
  - astro
  - express
  - frontend

# Settings <https://pnpm.io/settings>

## Dependency Resolution

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
  - vite@6.4.1
blockExoticSubdeps: true

## Build Settings

strictDepBuilds: true
onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
  - sharp
