/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NoName1 = string;
export type NoName3 = string;
export type NoName4 = number;
export type NoName5 = number;
export type NoName6 = number;
export type NoName7 = number;
export type NoName8 = number;
export type NoName10 = string;
export type NoName11 = string;
export type NoName9 = {
  filename: NoName10;
  caption: NoName11;
}[];

export interface NoName {
  view: View;
  icon: NoName2;
  icons: NoName9;
}
export interface View {
  init: NoName1;
}
export interface NoName2 {
  dir: NoName3;
  width: NoName4;
  height: NoName5;
  padding: NoName6;
  font_size: NoName7;
  line_height: NoName8;
}
