/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NoName1 = string;
export type NoName3 = string;
export type NoName4 = number;
export type NoName5 = number;
export type NoName6 = number;
export type NoName7 = number;
export type NoName8 = number;
export type NoName10 = string;
export type NoName11 = string;
export type NoName9 = {
  filename: NoName10;
  caption: NoName11;
}[];
export type NoName16 = number;
export type NoName19 = number;
export type NoName22 = number;
export type NoName25 = number;

export interface NoName {
  view: View;
  icon: NoName2;
  icons: NoName9;
  validator: NoName12;
}
export interface View {
  init: NoName1;
}
export interface NoName2 {
  dir: NoName3;
  width: NoName4;
  height: NoName5;
  padding: NoName6;
  font_size: NoName7;
  line_height: NoName8;
}
export interface NoName12 {
  icon: NoName13;
  text_right1: NoName15;
  text_right2: NoName18;
  text_left1: NoName21;
  text_left2: NoName24;
  color: NoName27;
  bgcolor: NoName29;
}
export interface NoName13 {
  message: NoName14;
}
export interface NoName14 {
  [k: string]: unknown;
}
export interface NoName15 {
  maxlength: NoName16;
  message: NoName17;
}
export interface NoName17 {
  [k: string]: unknown;
}
export interface NoName18 {
  maxlength: NoName19;
  message: NoName20;
}
export interface NoName20 {
  [k: string]: unknown;
}
export interface NoName21 {
  maxlength: NoName22;
  message: NoName23;
}
export interface NoName23 {
  [k: string]: unknown;
}
export interface NoName24 {
  maxlength: NoName25;
  message: NoName26;
}
export interface NoName26 {
  [k: string]: unknown;
}
export interface NoName27 {
  message: NoName28;
}
export interface NoName28 {
  [k: string]: unknown;
}
export interface NoName29 {
  message: NoName30;
}
export interface NoName30 {
  [k: string]: unknown;
}
