/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NoName = string;
export type JSONURL = string;
export type JSONURLLocal = string;

export interface Amazon {
  view: View;
  validator: NoName1;
  json_create: JSON;
}
export interface View {
  init: NoName;
}
export interface NoName1 {
  category: E;
}
export interface E {
  message: NoName2;
}
export interface NoName2 {
  [k: string]: unknown;
}
export interface JSON {
  url_base: JSONURL;
  url_base_local: JSONURLLocal;
  [k: string]: unknown;
}
