/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NoName1 = string;
export type NoName6 = string;
export type NoName8 = string;
export type NoName10 = string;
export type URL = string;
export type URLLocal = string;
export type NoName11 = string;
export type NoName12 = string;
export type URL1 = string;
export type URLLocal1 = string;
export type NoName13 = string;
export type NoName14 = string;
export type NoName15 = string;
export type URL2 = string;
export type URL3 = string;
export type APIKey = string;
export type APIKeySecret = string;
export type AccessToken = string;
export type AccessTokenSecret = string;
export type NoName17 = string;
export type NoName18 = string;
export type URL4 = string;
export type URLLocal2 = string;
export type NoName21 = number;
export type NoName22 = string;
export type NoName23 = number;
export type NoName24 = string;
export type NoName26 = number;
export type NoName27 = string;
export type NoName29 = number;
export type NoName30 = string;
export type NoName31 = string;

export interface NoName {
  view: View;
  validator: NoName2;
  insert: NoName5;
  update: NoName7;
  update_modified: NoName9;
  feed_create: Feed;
  newly_json_create: JSON;
  twitter: TwitterAPI;
  media_upload: NoName19;
}
export interface View {
  init: NoName1;
}
export interface NoName2 {
  title: NoName3;
}
export interface NoName3 {
  message: NoName4;
}
export interface NoName4 {
  [k: string]: unknown;
}
export interface NoName5 {
  success_message: NoName6;
}
export interface NoName7 {
  success_message: NoName8;
}
export interface NoName9 {
  success_message: NoName10;
}
export interface Feed {
  url: URL;
  url_local: URLLocal;
  api_response: API;
  [k: string]: unknown;
}
export interface API {
  success_message: NoName11;
  failure_message: NoName12;
}
export interface JSON {
  url: URL1;
  url_local: URLLocal1;
  api_response: API1;
  [k: string]: unknown;
}
export interface API1 {
  success_message: NoName13;
  failure_message: NoName14;
}
export interface TwitterAPI {
  message_prefix: NoName15;
  url_prefix: URL2;
  media_url_prefix: URL3;
  production: NoName16;
  api_response: API2;
}
export interface NoName16 {
  consumer_key: APIKey;
  consumer_secret: APIKeySecret;
  access_token: AccessToken;
  access_token_secret: AccessTokenSecret;
}
export interface API2 {
  success_message: NoName17;
  failure_message: NoName18;
}
export interface NoName19 {
  url: URL4;
  url_local: URLLocal2;
  api_response: API3;
  [k: string]: unknown;
}
export interface API3 {
  success: NoName20;
  type: MIME;
  overwrite: NoName25;
  size: NoName28;
  other_failure_message: NoName31;
}
export interface NoName20 {
  code: NoName21;
  message: NoName22;
}
export interface MIME {
  code: NoName23;
  message: NoName24;
}
export interface NoName25 {
  code: NoName26;
  message: NoName27;
}
export interface NoName28 {
  code: NoName29;
  message: NoName30;
}
