/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NoName7 = string;
export type NoName8 = string;
export type NoName9 = string;
export type NoName6 = {
  host: NoName7;
  name: NoName8;
  src: NoName9;
}[];
export type MIME = string;
export type NoName12 = string;
export type NoName13 = string;
export type NoName11 = {
  type: MIME;
  name: NoName12;
  src: NoName13;
}[];
export type HTML = string;
export type NoName18 = string;
export type NoName19 = string;
export type NoName20 = string;
export type Feed = string;
export type Feed1 = string;
export type NoName17 = {
  html_path: HTML;
  xpath: XPath;
  feed_template: Feed;
  feed_path: Feed1;
}[];

export interface NoName {
  html: {
    book: NoName1;
    newspaper: NoName2;
    section_id: ID;
    toc: NoName3;
    localnav: NoName4;
    anchor_host: NoName5;
    anchor_type: NoName10;
    anchor_amazon_associate: Amazon;
    heading_anchor: NoName14;
    time: Time;
    image: NoName15;
    image_amazon: Amazon1;
    highlight: NoName16;
  };
  feed: {
    info: NoName17;
  };
}
export interface NoName1 {
  target_element: string;
}
export interface NoName2 {
  target_element: string;
}
export interface ID {
  heading_levels: number[];
}
export interface NoName3 {
  target_element: string;
  class?: string;
  label?: string;
}
export interface NoName4 {
  target_class: string;
}
export interface NoName5 {
  target_class: string;
  insert_position: "beforebegin" | "afterbegin" | "beforeend" | "afterend";
  parentheses: {
    before: string;
    after: string;
  };
  element: string;
  class: string;
  icon: NoName6;
  icon_size: number;
  icon_class: string;
}
export interface NoName10 {
  target_class: string;
  insert_position: "beforebegin" | "afterbegin" | "beforeend" | "afterend";
  parentheses: {
    before: string;
    after: string;
  };
  icon: NoName11;
  icon_size: number;
  icon_class: string;
}
export interface Amazon {
  target_class: string;
}
export interface NoName14 {
  target_class: string;
  insert_position: "beforebegin" | "afterbegin" | "beforeend" | "afterend";
  anchor_class?: string;
}
export interface Time {
  target_class: string;
}
export interface NoName15 {
  target_class: string;
}
export interface Amazon1 {
  target_class: string;
}
export interface NoName16 {
  target_class: string;
  class_prefix: string;
}
export interface XPath {
  wrap: NoName18;
  date: NoName19;
  content: NoName20;
}
