/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HTTP = number;
export type StrictTransportSecurity = string;
export type ContentSecurityPolicyHTML = string;
export type ContentSecurityPolicyHTML1 = string;
export type ContentSecurityPolicyReportOnlyHTML = string;
export type Threshold = string;
export type NoName4 = string;
export type NoName5 = string[];
export type NoName6 = string[];
export type NoName8 = string[];
export type NoName9 = string[];
export type NoName11 = string;
export type NoName13 = string[];
export type NoName14 = string;
export type NoName12 = {
  paths: NoName13;
  value: NoName14;
}[];
export type NoName16 = string[];
export type NoName17 = string;
export type NoName15 = {
  extensions: NoName16;
  value: NoName17;
}[];
export type NoName18 = string[];
export type Directory = string[];
export type NoName19 = string;
export type Htpasswd = string;
export type BasicAuthentication = {
  directory: Directory;
  realm: NoName19;
  htpasswd: Htpasswd;
}[];
export type FilepathFor401Unauthorized = string;
export type FilepathFor403Forbidden = string;
export type FilepathFor404NotFound = string;
export type FilepathFor500InternalServerError = string;
export type NoName21 = string;
export type NoName22 = string;
export type NoName24 = string;
export type NoName25 = string;
export type Or = string;
export type NoName23 = {
  from: NoName24;
  to: NoName25;
  type: Or;
  [k: string]: unknown;
}[];
export type NoName26 = string;
export type AmazonAds = string;
export type Crawler = string;
export type Blog = string;
export type Tokyucarhistory = string;
export type Kumetatwitter = string;
export type Madokalibrary = string;
export type Madokawebarchive = string;
export type Madokatwitter = string;
export type APIKey = string;
export type APIKeySecret = string;
export type AccessToken = string;
export type AccessTokenSecret = string;
export type NoName28 = string;
/**
 * https://affiliate.amazon.co.jp/assoc_credentials/home
 */
export type NoName29 = string;
/**
 * https://affiliate.amazon.co.jp/assoc_credentials/home
 */
export type NoName30 = string;
/**
 * https://webservices.amazon.com/paapi5/documentation/locale-reference.html
 */
export type TargetAmazonLocale = string;
/**
 * https://webservices.amazon.com/paapi5/documentation/common-request-parameters.html#host-and-region
 */
export type TheHostValueOfTheTargetLocaleToWhichYouAreSendingRequests = string;
/**
 * https://webservices.amazon.com/paapi5/documentation/common-request-parameters.html#host-and-region
 */
export type TheAWSRegionOfTheTargetLocaleToWhichYouAreSendingRequests = string;

export interface W0SJp {
  port: HTTP;
  response: NoName;
  static: NoName3;
  errorpage: NoName20;
  views: NoName21;
  temp: NoName22;
  redirect: NoName23;
  logger: Logger;
  mail: EMail;
  sqlite: SQLite;
  twitter: TwitterAPI;
  paapi: AmazonProductAdvertisingAPI;
}
export interface NoName {
  header: NoName1;
  compression: NoName2;
}
export interface NoName1 {
  hsts: StrictTransportSecurity;
  csp: ContentSecurityPolicyHTML;
  csp_html: ContentSecurityPolicyHTML1;
  cspro_html: ContentSecurityPolicyReportOnlyHTML;
}
export interface NoName2 {
  threshold: Threshold;
}
export interface NoName3 {
  root: NoName4;
  extensions?: NoName5;
  indexes?: NoName6;
  headers: NoName7;
  auth_basic: BasicAuthentication;
}
export interface NoName7 {
  mime: MIME;
  cache_control?: NoName10;
  source_map?: SourceMap;
}
export interface MIME {
  path: MIME1;
  extension: MIME2;
}
export interface MIME1 {
  [k: string]: NoName8;
}
export interface MIME2 {
  [k: string]: NoName9;
}
export interface NoName10 {
  default: NoName11;
  path: NoName12;
  extension: NoName15;
}
export interface SourceMap {
  extensions?: NoName18;
}
export interface NoName20 {
  path_401: FilepathFor401Unauthorized;
  path_403: FilepathFor403Forbidden;
  path_404: FilepathFor404NotFound;
  path_500: FilepathFor500InternalServerError;
}
export interface Logger {
  path: NoName26;
}
export interface EMail {
  smtp: string;
  user: string;
  password: string;
  port: number;
  from: string;
  to: string;
}
export interface SQLite {
  db: DBNode;
}
export interface DBNode {
  amazon_ads: AmazonAds;
  crawler: Crawler;
  blog: Blog;
  tokyu_car_history: Tokyucarhistory;
  kumeta_twitter: Kumetatwitter;
  madoka_library: Madokalibrary;
  madoka_web_archive: Madokawebarchive;
  madoka_twitter: Madokatwitter;
}
export interface TwitterAPI {
  dev: NoName27;
}
export interface NoName27 {
  consumer_key: APIKey;
  consumer_secret: APIKeySecret;
  access_token: AccessToken;
  access_token_secret: AccessTokenSecret;
}
export interface AmazonProductAdvertisingAPI {
  request: CommonRequestParameters;
}
/**
 * https://webservices.amazon.com/paapi5/documentation/common-request-parameters.html
 */
export interface CommonRequestParameters {
  partner_tag: NoName28;
  access_key: NoName29;
  secret_key: NoName30;
  marketplace: TargetAmazonLocale;
  host: TheHostValueOfTheTargetLocaleToWhichYouAreSendingRequests;
  region: TheAWSRegionOfTheTargetLocaleToWhichYouAreSendingRequests;
}
