name: frontend@css-lint
on:
  push:
    branches:
      - main
    paths:
      - 'packages/frontend/public/assets/style/_src/**/*.css'
      - 'packages/frontend/.stylelintrc.json'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run css-lint -w '@w0s.jp/frontend'
