name: frontend@js-lint
on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/frontend/public/assets/script/_src/**/*.ts'
      - 'packages/.eslintrc.json'
  push:
    branches:
      - main
    paths:
      - 'packages/frontend/public/assets/script/_src/**/*.ts'
      - 'packages/.eslintrc.json'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run js-lint -w '@w0s.jp/frontend'
