name: frontend@node-test
on:
  push:
    branches:
      - main
    paths:
      - 'packages/frontend/node/src/**/*.ts'
      - 'packages/frontend/node/__tests__/**/*.test.js'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run node-test -w '@w0s.jp/frontend'
