name: html-lint
on:
  push:
    branches: 
      - main
    paths:
      - 'html/**/*.html'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run node-build-all
      - run: node node/dist/build/html.js html/**/*.html
      - run: npm run html-lint
